imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MarketplaceBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # cookie_lifetime: 1800 # deconnection au bout de 30 minutes -- 3600 = 1h
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        shop_name: MadininaMarket
        shop_tel: '+596 696 732 272'
        shop_email: contact@madininamarket.com
        shop_siret: '#siret ici'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
        
        

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    encryption: '%mailer_encryption%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: MarketplaceBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        product_image:
            uri_prefix:         /asset/img/products
            upload_destination: '%kernel.root_dir%/../web/asset/img/products'

            delete_on_remove: false
            delete_on_update: false
            inject_on_load: false

jms_i18n_routing:
    default_locale: '%locale%'
    locales: [fr, en]
    strategy: prefix_except_default

# doc : https://github.com/wdalmut/CorleyMaintenanceBundle
corley_maintenance:
    page: '%kernel.root_dir%/../web/maintenance.dist.html'
    hard_lock: lock.html
    symlink: false
    whitelist:  #url autorisées en mode maintenance
        paths:
            - sitemap #url du controlleur

# configuration JMS payment   http://jmspaymentcorebundle.readthedocs.io/en/stable/setup.html
jms_payment_core:
    encryption:
        secret: def0000039896b403d04d0d88f0cf4505d394fac95a9b4702d205ff5fe6d47c3f44ad040463099db98c449343c7853d21364c1855414e1bc8500cddb73ac39ef62bcf783 #bin/console jms_payment_core:generate-key

# paypal http://jmspaymentpaypalbundle.readthedocs.io/en/stable/setup.html
# https://developer.paypal.com/developer/accounts/
jms_payment_paypal:
    username: '%paypal_username%'
    password: '%paypal_psw%'
    signature: '%paypal_signature%'