marketplace:
    resource: "@MarketplaceBundle/Controller/"
    type:     annotation
   # shemes: [https] #pour forcer la route en https
  

seller:
    resource: "@MarketplaceBundle/Controller/Seller"
    type:     annotation
    prefix:   /seller
# shemes: [https] #pour forcer la route en https

back:
    resource: "@MarketplaceBundle/Controller/Back"
    type:     annotation
    prefix:   /admin
   # shemes: [https] #pour forcer la route en https 
 

# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"
