marketplace:
    resource: "@MarketplaceBundle/Controller/"
    type:     annotation
    prefix:   /

seller:
    resource: "@MarketplaceBundle/Controller/Seller"
    type:     annotation
    prefix:   /seller


back:
    resource: "@MarketplaceBundle/Controller/Back"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
