marketplace:
    resource: "@MarketplaceBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@MarketplaceBundle/Controller/Back"
    type:     annotation
    prefix:   /back

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
