marketplace:
    resource: "@MarketplaceBundle/Controller/"
    type:     annotation
    prefix:   /

back:
    resource: "@MarketplaceBundle/Controller/Back"
    type:     annotation
    prefix:   /back