<?php

namespace MarketplaceBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	// public function listAll()
	// {
	// 	$query = $this
	// 		->createQueryBuilder('c')
	// 		->select('c')
	// 		->orderBy('name');
	// 	return $query->getResult();
	// }
}
