<?php

namespace MarketplaceBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	// public function listAll()
	// {
	// 	$query = $this
	// 		->createQueryBuilder('c')
	// 		->select('c')
	// 		->orderBy('name');
	// 	return $query->getResult();
	// }

	public function itemsPerCategory($id)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'SELECT i.id, i.name, p.url, i.priceHt 
				FROM MarketplaceBundle:Items i, MarketplaceBundle:Picture p
				WHERE i.id = p.items
				AND i.category = :id
				')
			->setParameter('id',$id)
			;
		return $query->getResult();
	}
}
