<?php

namespace MarketplaceBundle\Repository;

/**
 * HistoryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
