<?php

namespace MarketplaceBundle\Repository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{
	public function gelAllItems()
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'SELECT i.id, i.name, p.url, i.priceHt 
				FROM MarketplaceBundle:Items i, MarketplaceBundle:Picture p
				WHERE i.id = p.items
				ORDER BY p.items
				');
		return $query->getResult();

		// $query = $this
		// 	->getEntityManager()
		// 	->createQuery(
		// 		'SELECT DISTINCT p.items
		// 		FROM MarketplaceBundle:Picture p
		// 		');
		// return $query->getResult();
		
		// $query = $this
		// 	->getEntityManager()
		// 	->createQuery(
		// 		'SELECT DISTINCT p.items, i.name, p.url, i.priceHt 
		// 		FROM MarketplaceBundle:Items i, MarketplaceBundle:Picture p
		// 		WHERE i.id = p.items
		// 		');
		// return $query->getResult();
		
		// $query = $this
		// 	->getEntityManager()
		// 	->createQuery(
		// 		'SELECT DISTINCT i, p
		// 		FROM MarketplaceBundle:Items i
		// 		WHERE i.id = p.id
		// 		IN (
		// 		SELECT DISTINCT p.items, p.id, p.url
		// 		FROM MarketplaceBundle:Picture p
		// 		)
		// 		');
		// return $query->getResult();
	}
}
