<?php

namespace MarketplaceBundle\Repository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends \Doctrine\ORM\EntityRepository
{
	public function findItemsInArray($array)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'
				SELECT i
				FROM  MarketplaceBundle:Items i
				WHERE i.id IN (:array)
				ORDER BY i.shop
				'
				)
			->setParameter("array",$array);
		return $query-> getResult();
	}

	public function searchItems($search)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				"
				SELECT i
				FROM MarketplaceBundle:Items i
				WHERE i.name LIKE  :search
				"
			)
			->setParameter("search", '%'.$search.'%');
		return $query->getResult();
	}

	public function searchItemsWithCat($cat, $search)
	{
		$params = ["search"=> '%'.$search.'%', "cat"=> $cat];

		$query = $this
			->getEntityManager()
			->createQuery(
				"
				SELECT i
				FROM MarketplaceBundle:Items i
				WHERE i.category = :cat
				AND i.name LIKE :search
				"
			)
			->setParameters($params);
		return $query-> getResult();
	}
}
