<?php

namespace MarketplaceBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOrdersArray($array)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'
				SELECT o
				FROM  MarketplaceBundle:Orders o
				WHERE o.id IN (:array)
				'
				)
			->setParameter("array",$array);
		return $query-> getResult();
	}
}
