<?php

namespace MarketplaceBundle\Repository;

/**
 * PicturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PicturesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getItemPic($id)
	{
		$query = $this
			->getEntityManager()
			->createQuery('SELECT p
				FROM  MarketplaceBundle:Picture p
				WHERE p.items = :id
				')
			->setParameter('id',$id);
		return $query->getResult();
	}
}
