<?php

namespace MarketplaceBundle\Repository;

/**
 * RefusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefusRepository extends \Doctrine\ORM\EntityRepository
{
}
