<?php

namespace MarketplaceBundle\Repository;

/**
 * ShipmentWayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentWayRepository extends \Doctrine\ORM\EntityRepository
{
}
