<?php

namespace MarketplaceBundle\Repository;

/**
 * ShipmentPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
