<?php

namespace MarketplaceBundle\Repository;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository
{
	# Récuperer les items lié aux shop
	public function findItemShop($array)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'
				SELECT s
				FROM  MarketplaceBundle:Items i, MarketplaceBundle:Shop s
				WHERE i.shop = s.id
				AND i.id IN (:array)
				ORDER BY i.shop	
				'
				)
			->setParameter("array",$array);
		$res = $query-> getResult();

		// $shop = [];

		// foreach ($res as  $value) 
		// {
		// 	$shop[] = $value->getShop();
		// }

		// return $shop;
		return $res;
	}
}