<?php

namespace MarketplaceBundle\Repository;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends \Doctrine\ORM\EntityRepository
{
	# Récuperer les items lié aux shop
	public function findItems($id)
	{
		$query = $this
			->getEntityManager()
			->createQuery(
				'SELECT i.id, i.name, p.url, i.priceHt 
				FROM MarketplaceBundle:Items i, MarketplaceBundle:Picture p
				WHERE i.id = p.items
				AND i.shop = :id
				')
			->setParameter('id',$id)
			;
		return $query->getResult();
	}
}
