<?php

namespace MarketplaceBundle\Repository;

/**
 * SoldItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldItemRepository extends \Doctrine\ORM\EntityRepository
{
}
